/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as HomeRouteImport } from './routes/home'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SiteEditorRouteImport } from './routes/site-editor'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as DocumentIdRouteImport } from './routes/document.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteEditorRoute = SiteEditorRouteImport.update({
  id: '/site-editor',
  path: '/site-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentIdRoute = DocumentIdRouteImport.update({
  id: '/document/$id',
  path: '/document/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/browse': typeof BrowseRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/home': typeof HomeRoute
  '/owner': typeof OwnerRoute
  '/profile': typeof ProfileRoute
  '/site-editor': typeof SiteEditorRoute
  '/upload': typeof UploadRoute
  '/document/$id': typeof DocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/browse': typeof BrowseRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/home': typeof HomeRoute
  '/owner': typeof OwnerRoute
  '/profile': typeof ProfileRoute
  '/site-editor': typeof SiteEditorRoute
  '/upload': typeof UploadRoute
  '/document/$id': typeof DocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/browse': typeof BrowseRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/home': typeof HomeRoute
  '/owner': typeof OwnerRoute
  '/profile': typeof ProfileRoute
  '/site-editor': typeof SiteEditorRoute
  '/upload': typeof UploadRoute
  '/document/$id': typeof DocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/browse'
    | '/complete-profile'
    | '/home'
    | '/owner'
    | '/profile'
    | '/site-editor'
    | '/upload'
    | '/document/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/browse'
    | '/complete-profile'
    | '/home'
    | '/owner'
    | '/profile'
    | '/site-editor'
    | '/upload'
    | '/document/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/browse'
    | '/complete-profile'
    | '/home'
    | '/owner'
    | '/profile'
    | '/site-editor'
    | '/upload'
    | '/document/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BrowseRoute: typeof BrowseRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  HomeRoute: typeof HomeRoute
  OwnerRoute: typeof OwnerRoute
  ProfileRoute: typeof ProfileRoute
  SiteEditorRoute: typeof SiteEditorRoute
  UploadRoute: typeof UploadRoute
  DocumentIdRoute: typeof DocumentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-editor': {
      id: '/site-editor'
      path: '/site-editor'
      fullPath: '/site-editor'
      preLoaderRoute: typeof SiteEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/$id': {
      id: '/document/$id'
      path: '/document/$id'
      fullPath: '/document/$id'
      preLoaderRoute: typeof DocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  BrowseRoute: BrowseRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  HomeRoute: HomeRoute,
  OwnerRoute: OwnerRoute,
  ProfileRoute: ProfileRoute,
  SiteEditorRoute: SiteEditorRoute,
  UploadRoute: UploadRoute,
  DocumentIdRoute: DocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
